### ISSUE TITLE
Move tcgui identifier to second line down rather than 3rd

### ISSUE THREAD

**Issue by DNAmaster10** [DNAmaster10/TraincartsGui#32]

**Comment by Dinty1** [comment]
On other plugins this tends to go on the first line

**Comment by DNAmaster10** [comment]
> On other plugins this tends to go on the first line

I thought it might be better to put in on the second line, as this is what MyWarps already does. Would make for a bit more consistency within transit, although Traincarts goes on the top, so maybe the top line would be best.

Actually, we may as well make it a config option, so servers can change it if they want
